/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AudioAnalyticsRouteImport } from './routes/audio-analytics'
import { Route as CrmStagesRouteImport } from './routes/crm-stages'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FunnelsRouteImport } from './routes/funnels'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LeadAnalyticsRouteImport } from './routes/lead-analytics'
import { Route as LeadTasksRouteImport } from './routes/lead-tasks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminAiAgentsRouteImport } from './routes/admin.ai-agents'
import { Route as AdminAmocrmCatalogRouteImport } from './routes/admin.amocrm-catalog'
import { Route as AdminAmocrmDisconnectRouteImport } from './routes/admin.amocrm-disconnect'
import { Route as AdminAmocrmImportRouteImport } from './routes/admin.amocrm-import'
import { Route as AdminAmocrmImportSettingsRouteImport } from './routes/admin.amocrm-import-settings'
import { Route as AdminAutoRespondersRouteImport } from './routes/admin.auto-responders'
import { Route as AdminCreateEmployeeRouteImport } from './routes/admin.create-employee'
import { Route as AdminDeleteEmployeeRouteImport } from './routes/admin.delete-employee'
import { Route as AdminOrgStructureRouteImport } from './routes/admin.org-structure'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminSecurityBanRouteImport } from './routes/admin.security-ban'
import { Route as AdminSecurityUsersRouteImport } from './routes/admin.security-users'
import { Route as AdminSetEmployeePasswordRouteImport } from './routes/admin.set-employee-password'
import { Route as AiAssistantChatRouteImport } from './routes/ai-assistant.chat'
import { Route as AudioAnalyticsAnalyzeRouteImport } from './routes/audio-analytics.analyze'
import { Route as CrmCompaniesRouteImport } from './routes/crm.companies'
import { Route as CrmContactsRouteImport } from './routes/crm.contacts'
import { Route as CrmDealsRouteImport } from './routes/crm.deals'
import { Route as CrmPipelineRouteImport } from './routes/crm.pipeline'
import { Route as DashboardAmocrmTasksRouteImport } from './routes/dashboard.amocrm-tasks'
import { Route as ErrorsLogRouteImport } from './routes/errors.log'
import { Route as NotificationsSendPushRouteImport } from './routes/notifications.send-push'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformActivityRouteImport } from './routes/platform.activity'
import { Route as PlatformAddEmployeeRouteImport } from './routes/platform.add-employee'
import { Route as PlatformAiRouteImport } from './routes/platform.ai'
import { Route as PlatformCreateOrganizationRouteImport } from './routes/platform.create-organization'
import { Route as PlatformDeactivateExpiredTrialsRouteImport } from './routes/platform.deactivate-expired-trials'
import { Route as PlatformDeleteOrganizationRouteImport } from './routes/platform.delete-organization'
import { Route as PlatformDeleteUserRouteImport } from './routes/platform.delete-user'
import { Route as PlatformErrorsRouteImport } from './routes/platform.errors'
import { Route as PlatformIntegrationsRouteImport } from './routes/platform.integrations'
import { Route as PlatformNotificationsRouteImport } from './routes/platform.notifications'
import { Route as PlatformUpdateUserRouteImport } from './routes/platform.update-user'
import { Route as PlatformUsersRouteImport } from './routes/platform.users'
import { Route as TelegramLinkRouteImport } from './routes/telegram.link'
import { Route as TelegramSendDailyReportRouteImport } from './routes/telegram.send-daily-report'
import { Route as TelegramSendTestRouteImport } from './routes/telegram.send-test'
import { Route as TelegramWebhookRouteImport } from './routes/telegram.webhook'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as CrmLeadsIndexRouteImport } from './routes/crm.leads.index'
import { Route as CrmLeadsLeadIdRouteImport } from './routes/crm.leads.$leadId'
import { Route as IntegrationsAmocrmCallbackRouteImport } from './routes/integrations.amocrm.callback'
import { Route as IntegrationsAmocrmConnectRouteImport } from './routes/integrations.amocrm.connect'
import { Route as IntegrationsAmocrmSyncRouteImport } from './routes/integrations.amocrm.sync'
import { Route as IntegrationsAmocrmSyncAllRouteImport } from './routes/integrations.amocrm.sync-all'
import { Route as IntegrationsAmocrmWebhookRouteImport } from './routes/integrations.amocrm.webhook'
import { Route as PlatformOrganizationsOrgIdRouteImport } from './routes/platform.organizations.$orgId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioAnalyticsRoute = AudioAnalyticsRouteImport.update({
  id: '/audio-analytics',
  path: '/audio-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmStagesRoute = CrmStagesRouteImport.update({
  id: '/crm-stages',
  path: '/crm-stages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelsRoute = FunnelsRouteImport.update({
  id: '/funnels',
  path: '/funnels',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadAnalyticsRoute = LeadAnalyticsRouteImport.update({
  id: '/lead-analytics',
  path: '/lead-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadTasksRoute = LeadTasksRouteImport.update({
  id: '/lead-tasks',
  path: '/lead-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAiAgentsRoute = AdminAiAgentsRouteImport.update({
  id: '/ai-agents',
  path: '/ai-agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmocrmCatalogRoute = AdminAmocrmCatalogRouteImport.update({
  id: '/amocrm-catalog',
  path: '/amocrm-catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmocrmDisconnectRoute = AdminAmocrmDisconnectRouteImport.update({
  id: '/amocrm-disconnect',
  path: '/amocrm-disconnect',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmocrmImportRoute = AdminAmocrmImportRouteImport.update({
  id: '/amocrm-import',
  path: '/amocrm-import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmocrmImportSettingsRoute =
  AdminAmocrmImportSettingsRouteImport.update({
    id: '/amocrm-import-settings',
    path: '/amocrm-import-settings',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAutoRespondersRoute = AdminAutoRespondersRouteImport.update({
  id: '/auto-responders',
  path: '/auto-responders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreateEmployeeRoute = AdminCreateEmployeeRouteImport.update({
  id: '/create-employee',
  path: '/create-employee',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeleteEmployeeRoute = AdminDeleteEmployeeRouteImport.update({
  id: '/delete-employee',
  path: '/delete-employee',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgStructureRoute = AdminOrgStructureRouteImport.update({
  id: '/org-structure',
  path: '/org-structure',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityBanRoute = AdminSecurityBanRouteImport.update({
  id: '/security-ban',
  path: '/security-ban',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityUsersRoute = AdminSecurityUsersRouteImport.update({
  id: '/security-users',
  path: '/security-users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetEmployeePasswordRoute =
  AdminSetEmployeePasswordRouteImport.update({
    id: '/set-employee-password',
    path: '/set-employee-password',
    getParentRoute: () => AdminRoute,
  } as any)
const AiAssistantChatRoute = AiAssistantChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AiAssistantRoute,
} as any)
const AudioAnalyticsAnalyzeRoute = AudioAnalyticsAnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => AudioAnalyticsRoute,
} as any)
const CrmCompaniesRoute = CrmCompaniesRouteImport.update({
  id: '/crm/companies',
  path: '/crm/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/crm/contacts',
  path: '/crm/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmDealsRoute = CrmDealsRouteImport.update({
  id: '/crm/deals',
  path: '/crm/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmPipelineRoute = CrmPipelineRouteImport.update({
  id: '/crm/pipeline',
  path: '/crm/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAmocrmTasksRoute = DashboardAmocrmTasksRouteImport.update({
  id: '/amocrm-tasks',
  path: '/amocrm-tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const ErrorsLogRoute = ErrorsLogRouteImport.update({
  id: '/errors/log',
  path: '/errors/log',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsSendPushRoute = NotificationsSendPushRouteImport.update({
  id: '/notifications/send-push',
  path: '/notifications/send-push',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/platform/',
  path: '/platform/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformActivityRoute = PlatformActivityRouteImport.update({
  id: '/platform/activity',
  path: '/platform/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAddEmployeeRoute = PlatformAddEmployeeRouteImport.update({
  id: '/platform/add-employee',
  path: '/platform/add-employee',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAiRoute = PlatformAiRouteImport.update({
  id: '/platform/ai',
  path: '/platform/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformCreateOrganizationRoute =
  PlatformCreateOrganizationRouteImport.update({
    id: '/platform/create-organization',
    path: '/platform/create-organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformDeactivateExpiredTrialsRoute =
  PlatformDeactivateExpiredTrialsRouteImport.update({
    id: '/platform/deactivate-expired-trials',
    path: '/platform/deactivate-expired-trials',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformDeleteOrganizationRoute =
  PlatformDeleteOrganizationRouteImport.update({
    id: '/platform/delete-organization',
    path: '/platform/delete-organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformDeleteUserRoute = PlatformDeleteUserRouteImport.update({
  id: '/platform/delete-user',
  path: '/platform/delete-user',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformErrorsRoute = PlatformErrorsRouteImport.update({
  id: '/platform/errors',
  path: '/platform/errors',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIntegrationsRoute = PlatformIntegrationsRouteImport.update({
  id: '/platform/integrations',
  path: '/platform/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformNotificationsRoute = PlatformNotificationsRouteImport.update({
  id: '/platform/notifications',
  path: '/platform/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformUpdateUserRoute = PlatformUpdateUserRouteImport.update({
  id: '/platform/update-user',
  path: '/platform/update-user',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformUsersRoute = PlatformUsersRouteImport.update({
  id: '/platform/users',
  path: '/platform/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramLinkRoute = TelegramLinkRouteImport.update({
  id: '/telegram/link',
  path: '/telegram/link',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramSendDailyReportRoute = TelegramSendDailyReportRouteImport.update({
  id: '/telegram/send-daily-report',
  path: '/telegram/send-daily-report',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramSendTestRoute = TelegramSendTestRouteImport.update({
  id: '/telegram/send-test',
  path: '/telegram/send-test',
  getParentRoute: () => rootRouteImport,
} as any)
const TelegramWebhookRoute = TelegramWebhookRouteImport.update({
  id: '/telegram/webhook',
  path: '/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrmLeadsIndexRoute = CrmLeadsIndexRouteImport.update({
  id: '/crm/leads/',
  path: '/crm/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsLeadIdRoute = CrmLeadsLeadIdRouteImport.update({
  id: '/crm/leads/$leadId',
  path: '/crm/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsAmocrmCallbackRoute =
  IntegrationsAmocrmCallbackRouteImport.update({
    id: '/amocrm/callback',
    path: '/amocrm/callback',
    getParentRoute: () => IntegrationsRoute,
  } as any)
const IntegrationsAmocrmConnectRoute =
  IntegrationsAmocrmConnectRouteImport.update({
    id: '/amocrm/connect',
    path: '/amocrm/connect',
    getParentRoute: () => IntegrationsRoute,
  } as any)
const IntegrationsAmocrmSyncRoute = IntegrationsAmocrmSyncRouteImport.update({
  id: '/amocrm/sync',
  path: '/amocrm/sync',
  getParentRoute: () => IntegrationsRoute,
} as any)
const IntegrationsAmocrmSyncAllRoute =
  IntegrationsAmocrmSyncAllRouteImport.update({
    id: '/amocrm/sync-all',
    path: '/amocrm/sync-all',
    getParentRoute: () => IntegrationsRoute,
  } as any)
const IntegrationsAmocrmWebhookRoute =
  IntegrationsAmocrmWebhookRouteImport.update({
    id: '/amocrm/webhook',
    path: '/amocrm/webhook',
    getParentRoute: () => IntegrationsRoute,
  } as any)
const PlatformOrganizationsOrgIdRoute =
  PlatformOrganizationsOrgIdRouteImport.update({
    id: '/platform/organizations/$orgId',
    path: '/platform/organizations/$orgId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-assistant': typeof AiAssistantRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/audio-analytics': typeof AudioAnalyticsRouteWithChildren
  '/crm-stages': typeof CrmStagesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/funnels': typeof FunnelsRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/lead-analytics': typeof LeadAnalyticsRoute
  '/lead-tasks': typeof LeadTasksRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ai-agents': typeof AdminAiAgentsRoute
  '/admin/amocrm-catalog': typeof AdminAmocrmCatalogRoute
  '/admin/amocrm-disconnect': typeof AdminAmocrmDisconnectRoute
  '/admin/amocrm-import': typeof AdminAmocrmImportRoute
  '/admin/amocrm-import-settings': typeof AdminAmocrmImportSettingsRoute
  '/admin/auto-responders': typeof AdminAutoRespondersRoute
  '/admin/create-employee': typeof AdminCreateEmployeeRoute
  '/admin/delete-employee': typeof AdminDeleteEmployeeRoute
  '/admin/org-structure': typeof AdminOrgStructureRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/security-ban': typeof AdminSecurityBanRoute
  '/admin/security-users': typeof AdminSecurityUsersRoute
  '/admin/set-employee-password': typeof AdminSetEmployeePasswordRoute
  '/ai-assistant/chat': typeof AiAssistantChatRoute
  '/audio-analytics/analyze': typeof AudioAnalyticsAnalyzeRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/dashboard/amocrm-tasks': typeof DashboardAmocrmTasksRoute
  '/errors/log': typeof ErrorsLogRoute
  '/notifications/send-push': typeof NotificationsSendPushRoute
  '/platform/activity': typeof PlatformActivityRoute
  '/platform/add-employee': typeof PlatformAddEmployeeRoute
  '/platform/ai': typeof PlatformAiRoute
  '/platform/create-organization': typeof PlatformCreateOrganizationRoute
  '/platform/deactivate-expired-trials': typeof PlatformDeactivateExpiredTrialsRoute
  '/platform/delete-organization': typeof PlatformDeleteOrganizationRoute
  '/platform/delete-user': typeof PlatformDeleteUserRoute
  '/platform/errors': typeof PlatformErrorsRoute
  '/platform/integrations': typeof PlatformIntegrationsRoute
  '/platform/notifications': typeof PlatformNotificationsRoute
  '/platform/update-user': typeof PlatformUpdateUserRoute
  '/platform/users': typeof PlatformUsersRoute
  '/telegram/link': typeof TelegramLinkRoute
  '/telegram/send-daily-report': typeof TelegramSendDailyReportRoute
  '/telegram/send-test': typeof TelegramSendTestRoute
  '/telegram/webhook': typeof TelegramWebhookRoute
  '/platform/': typeof PlatformIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/crm/leads/$leadId': typeof CrmLeadsLeadIdRoute
  '/integrations/amocrm/callback': typeof IntegrationsAmocrmCallbackRoute
  '/integrations/amocrm/connect': typeof IntegrationsAmocrmConnectRoute
  '/integrations/amocrm/sync': typeof IntegrationsAmocrmSyncRoute
  '/integrations/amocrm/sync-all': typeof IntegrationsAmocrmSyncAllRoute
  '/integrations/amocrm/webhook': typeof IntegrationsAmocrmWebhookRoute
  '/platform/organizations/$orgId': typeof PlatformOrganizationsOrgIdRoute
  '/crm/leads/': typeof CrmLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-assistant': typeof AiAssistantRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/audio-analytics': typeof AudioAnalyticsRouteWithChildren
  '/crm-stages': typeof CrmStagesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/funnels': typeof FunnelsRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/lead-analytics': typeof LeadAnalyticsRoute
  '/lead-tasks': typeof LeadTasksRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ai-agents': typeof AdminAiAgentsRoute
  '/admin/amocrm-catalog': typeof AdminAmocrmCatalogRoute
  '/admin/amocrm-disconnect': typeof AdminAmocrmDisconnectRoute
  '/admin/amocrm-import': typeof AdminAmocrmImportRoute
  '/admin/amocrm-import-settings': typeof AdminAmocrmImportSettingsRoute
  '/admin/auto-responders': typeof AdminAutoRespondersRoute
  '/admin/create-employee': typeof AdminCreateEmployeeRoute
  '/admin/delete-employee': typeof AdminDeleteEmployeeRoute
  '/admin/org-structure': typeof AdminOrgStructureRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/security-ban': typeof AdminSecurityBanRoute
  '/admin/security-users': typeof AdminSecurityUsersRoute
  '/admin/set-employee-password': typeof AdminSetEmployeePasswordRoute
  '/ai-assistant/chat': typeof AiAssistantChatRoute
  '/audio-analytics/analyze': typeof AudioAnalyticsAnalyzeRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/dashboard/amocrm-tasks': typeof DashboardAmocrmTasksRoute
  '/errors/log': typeof ErrorsLogRoute
  '/notifications/send-push': typeof NotificationsSendPushRoute
  '/platform/activity': typeof PlatformActivityRoute
  '/platform/add-employee': typeof PlatformAddEmployeeRoute
  '/platform/ai': typeof PlatformAiRoute
  '/platform/create-organization': typeof PlatformCreateOrganizationRoute
  '/platform/deactivate-expired-trials': typeof PlatformDeactivateExpiredTrialsRoute
  '/platform/delete-organization': typeof PlatformDeleteOrganizationRoute
  '/platform/delete-user': typeof PlatformDeleteUserRoute
  '/platform/errors': typeof PlatformErrorsRoute
  '/platform/integrations': typeof PlatformIntegrationsRoute
  '/platform/notifications': typeof PlatformNotificationsRoute
  '/platform/update-user': typeof PlatformUpdateUserRoute
  '/platform/users': typeof PlatformUsersRoute
  '/telegram/link': typeof TelegramLinkRoute
  '/telegram/send-daily-report': typeof TelegramSendDailyReportRoute
  '/telegram/send-test': typeof TelegramSendTestRoute
  '/telegram/webhook': typeof TelegramWebhookRoute
  '/platform': typeof PlatformIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/crm/leads/$leadId': typeof CrmLeadsLeadIdRoute
  '/integrations/amocrm/callback': typeof IntegrationsAmocrmCallbackRoute
  '/integrations/amocrm/connect': typeof IntegrationsAmocrmConnectRoute
  '/integrations/amocrm/sync': typeof IntegrationsAmocrmSyncRoute
  '/integrations/amocrm/sync-all': typeof IntegrationsAmocrmSyncAllRoute
  '/integrations/amocrm/webhook': typeof IntegrationsAmocrmWebhookRoute
  '/platform/organizations/$orgId': typeof PlatformOrganizationsOrgIdRoute
  '/crm/leads': typeof CrmLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-assistant': typeof AiAssistantRouteWithChildren
  '/attendance': typeof AttendanceRoute
  '/audio-analytics': typeof AudioAnalyticsRouteWithChildren
  '/crm-stages': typeof CrmStagesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/funnels': typeof FunnelsRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRouteWithChildren
  '/lead-analytics': typeof LeadAnalyticsRoute
  '/lead-tasks': typeof LeadTasksRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ai-agents': typeof AdminAiAgentsRoute
  '/admin/amocrm-catalog': typeof AdminAmocrmCatalogRoute
  '/admin/amocrm-disconnect': typeof AdminAmocrmDisconnectRoute
  '/admin/amocrm-import': typeof AdminAmocrmImportRoute
  '/admin/amocrm-import-settings': typeof AdminAmocrmImportSettingsRoute
  '/admin/auto-responders': typeof AdminAutoRespondersRoute
  '/admin/create-employee': typeof AdminCreateEmployeeRoute
  '/admin/delete-employee': typeof AdminDeleteEmployeeRoute
  '/admin/org-structure': typeof AdminOrgStructureRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/security-ban': typeof AdminSecurityBanRoute
  '/admin/security-users': typeof AdminSecurityUsersRoute
  '/admin/set-employee-password': typeof AdminSetEmployeePasswordRoute
  '/ai-assistant/chat': typeof AiAssistantChatRoute
  '/audio-analytics/analyze': typeof AudioAnalyticsAnalyzeRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/dashboard/amocrm-tasks': typeof DashboardAmocrmTasksRoute
  '/errors/log': typeof ErrorsLogRoute
  '/notifications/send-push': typeof NotificationsSendPushRoute
  '/platform/activity': typeof PlatformActivityRoute
  '/platform/add-employee': typeof PlatformAddEmployeeRoute
  '/platform/ai': typeof PlatformAiRoute
  '/platform/create-organization': typeof PlatformCreateOrganizationRoute
  '/platform/deactivate-expired-trials': typeof PlatformDeactivateExpiredTrialsRoute
  '/platform/delete-organization': typeof PlatformDeleteOrganizationRoute
  '/platform/delete-user': typeof PlatformDeleteUserRoute
  '/platform/errors': typeof PlatformErrorsRoute
  '/platform/integrations': typeof PlatformIntegrationsRoute
  '/platform/notifications': typeof PlatformNotificationsRoute
  '/platform/update-user': typeof PlatformUpdateUserRoute
  '/platform/users': typeof PlatformUsersRoute
  '/telegram/link': typeof TelegramLinkRoute
  '/telegram/send-daily-report': typeof TelegramSendDailyReportRoute
  '/telegram/send-test': typeof TelegramSendTestRoute
  '/telegram/webhook': typeof TelegramWebhookRoute
  '/platform/': typeof PlatformIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/crm/leads/$leadId': typeof CrmLeadsLeadIdRoute
  '/integrations/amocrm/callback': typeof IntegrationsAmocrmCallbackRoute
  '/integrations/amocrm/connect': typeof IntegrationsAmocrmConnectRoute
  '/integrations/amocrm/sync': typeof IntegrationsAmocrmSyncRoute
  '/integrations/amocrm/sync-all': typeof IntegrationsAmocrmSyncAllRoute
  '/integrations/amocrm/webhook': typeof IntegrationsAmocrmWebhookRoute
  '/platform/organizations/$orgId': typeof PlatformOrganizationsOrgIdRoute
  '/crm/leads/': typeof CrmLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/attendance'
    | '/audio-analytics'
    | '/crm-stages'
    | '/dashboard'
    | '/funnels'
    | '/inbox'
    | '/integrations'
    | '/lead-analytics'
    | '/lead-tasks'
    | '/login'
    | '/mcp'
    | '/settings'
    | '/sitemap.xml'
    | '/tasks'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ai-agents'
    | '/admin/amocrm-catalog'
    | '/admin/amocrm-disconnect'
    | '/admin/amocrm-import'
    | '/admin/amocrm-import-settings'
    | '/admin/auto-responders'
    | '/admin/create-employee'
    | '/admin/delete-employee'
    | '/admin/org-structure'
    | '/admin/permissions'
    | '/admin/security'
    | '/admin/security-ban'
    | '/admin/security-users'
    | '/admin/set-employee-password'
    | '/ai-assistant/chat'
    | '/audio-analytics/analyze'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/crm/pipeline'
    | '/dashboard/amocrm-tasks'
    | '/errors/log'
    | '/notifications/send-push'
    | '/platform/activity'
    | '/platform/add-employee'
    | '/platform/ai'
    | '/platform/create-organization'
    | '/platform/deactivate-expired-trials'
    | '/platform/delete-organization'
    | '/platform/delete-user'
    | '/platform/errors'
    | '/platform/integrations'
    | '/platform/notifications'
    | '/platform/update-user'
    | '/platform/users'
    | '/telegram/link'
    | '/telegram/send-daily-report'
    | '/telegram/send-test'
    | '/telegram/webhook'
    | '/platform/'
    | '/.mcp/invoke-tool/$tool'
    | '/crm/leads/$leadId'
    | '/integrations/amocrm/callback'
    | '/integrations/amocrm/connect'
    | '/integrations/amocrm/sync'
    | '/integrations/amocrm/sync-all'
    | '/integrations/amocrm/webhook'
    | '/platform/organizations/$orgId'
    | '/crm/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/attendance'
    | '/audio-analytics'
    | '/crm-stages'
    | '/dashboard'
    | '/funnels'
    | '/inbox'
    | '/integrations'
    | '/lead-analytics'
    | '/lead-tasks'
    | '/login'
    | '/mcp'
    | '/settings'
    | '/sitemap.xml'
    | '/tasks'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ai-agents'
    | '/admin/amocrm-catalog'
    | '/admin/amocrm-disconnect'
    | '/admin/amocrm-import'
    | '/admin/amocrm-import-settings'
    | '/admin/auto-responders'
    | '/admin/create-employee'
    | '/admin/delete-employee'
    | '/admin/org-structure'
    | '/admin/permissions'
    | '/admin/security'
    | '/admin/security-ban'
    | '/admin/security-users'
    | '/admin/set-employee-password'
    | '/ai-assistant/chat'
    | '/audio-analytics/analyze'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/crm/pipeline'
    | '/dashboard/amocrm-tasks'
    | '/errors/log'
    | '/notifications/send-push'
    | '/platform/activity'
    | '/platform/add-employee'
    | '/platform/ai'
    | '/platform/create-organization'
    | '/platform/deactivate-expired-trials'
    | '/platform/delete-organization'
    | '/platform/delete-user'
    | '/platform/errors'
    | '/platform/integrations'
    | '/platform/notifications'
    | '/platform/update-user'
    | '/platform/users'
    | '/telegram/link'
    | '/telegram/send-daily-report'
    | '/telegram/send-test'
    | '/telegram/webhook'
    | '/platform'
    | '/.mcp/invoke-tool/$tool'
    | '/crm/leads/$leadId'
    | '/integrations/amocrm/callback'
    | '/integrations/amocrm/connect'
    | '/integrations/amocrm/sync'
    | '/integrations/amocrm/sync-all'
    | '/integrations/amocrm/webhook'
    | '/platform/organizations/$orgId'
    | '/crm/leads'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-assistant'
    | '/attendance'
    | '/audio-analytics'
    | '/crm-stages'
    | '/dashboard'
    | '/funnels'
    | '/inbox'
    | '/integrations'
    | '/lead-analytics'
    | '/lead-tasks'
    | '/login'
    | '/mcp'
    | '/settings'
    | '/sitemap.xml'
    | '/tasks'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ai-agents'
    | '/admin/amocrm-catalog'
    | '/admin/amocrm-disconnect'
    | '/admin/amocrm-import'
    | '/admin/amocrm-import-settings'
    | '/admin/auto-responders'
    | '/admin/create-employee'
    | '/admin/delete-employee'
    | '/admin/org-structure'
    | '/admin/permissions'
    | '/admin/security'
    | '/admin/security-ban'
    | '/admin/security-users'
    | '/admin/set-employee-password'
    | '/ai-assistant/chat'
    | '/audio-analytics/analyze'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/crm/pipeline'
    | '/dashboard/amocrm-tasks'
    | '/errors/log'
    | '/notifications/send-push'
    | '/platform/activity'
    | '/platform/add-employee'
    | '/platform/ai'
    | '/platform/create-organization'
    | '/platform/deactivate-expired-trials'
    | '/platform/delete-organization'
    | '/platform/delete-user'
    | '/platform/errors'
    | '/platform/integrations'
    | '/platform/notifications'
    | '/platform/update-user'
    | '/platform/users'
    | '/telegram/link'
    | '/telegram/send-daily-report'
    | '/telegram/send-test'
    | '/telegram/webhook'
    | '/platform/'
    | '/.mcp/invoke-tool/$tool'
    | '/crm/leads/$leadId'
    | '/integrations/amocrm/callback'
    | '/integrations/amocrm/connect'
    | '/integrations/amocrm/sync'
    | '/integrations/amocrm/sync-all'
    | '/integrations/amocrm/webhook'
    | '/platform/organizations/$orgId'
    | '/crm/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiAssistantRoute: typeof AiAssistantRouteWithChildren
  AttendanceRoute: typeof AttendanceRoute
  AudioAnalyticsRoute: typeof AudioAnalyticsRouteWithChildren
  CrmStagesRoute: typeof CrmStagesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FunnelsRoute: typeof FunnelsRoute
  InboxRoute: typeof InboxRoute
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  LeadAnalyticsRoute: typeof LeadAnalyticsRoute
  LeadTasksRoute: typeof LeadTasksRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TasksRoute: typeof TasksRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CrmCompaniesRoute: typeof CrmCompaniesRoute
  CrmContactsRoute: typeof CrmContactsRoute
  CrmDealsRoute: typeof CrmDealsRoute
  CrmPipelineRoute: typeof CrmPipelineRoute
  ErrorsLogRoute: typeof ErrorsLogRoute
  NotificationsSendPushRoute: typeof NotificationsSendPushRoute
  PlatformActivityRoute: typeof PlatformActivityRoute
  PlatformAddEmployeeRoute: typeof PlatformAddEmployeeRoute
  PlatformAiRoute: typeof PlatformAiRoute
  PlatformCreateOrganizationRoute: typeof PlatformCreateOrganizationRoute
  PlatformDeactivateExpiredTrialsRoute: typeof PlatformDeactivateExpiredTrialsRoute
  PlatformDeleteOrganizationRoute: typeof PlatformDeleteOrganizationRoute
  PlatformDeleteUserRoute: typeof PlatformDeleteUserRoute
  PlatformErrorsRoute: typeof PlatformErrorsRoute
  PlatformIntegrationsRoute: typeof PlatformIntegrationsRoute
  PlatformNotificationsRoute: typeof PlatformNotificationsRoute
  PlatformUpdateUserRoute: typeof PlatformUpdateUserRoute
  PlatformUsersRoute: typeof PlatformUsersRoute
  TelegramLinkRoute: typeof TelegramLinkRoute
  TelegramSendDailyReportRoute: typeof TelegramSendDailyReportRoute
  TelegramSendTestRoute: typeof TelegramSendTestRoute
  TelegramWebhookRoute: typeof TelegramWebhookRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  CrmLeadsLeadIdRoute: typeof CrmLeadsLeadIdRoute
  PlatformOrganizationsOrgIdRoute: typeof PlatformOrganizationsOrgIdRoute
  CrmLeadsIndexRoute: typeof CrmLeadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-analytics': {
      id: '/audio-analytics'
      path: '/audio-analytics'
      fullPath: '/audio-analytics'
      preLoaderRoute: typeof AudioAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm-stages': {
      id: '/crm-stages'
      path: '/crm-stages'
      fullPath: '/crm-stages'
      preLoaderRoute: typeof CrmStagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnels': {
      id: '/funnels'
      path: '/funnels'
      fullPath: '/funnels'
      preLoaderRoute: typeof FunnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-analytics': {
      id: '/lead-analytics'
      path: '/lead-analytics'
      fullPath: '/lead-analytics'
      preLoaderRoute: typeof LeadAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-tasks': {
      id: '/lead-tasks'
      path: '/lead-tasks'
      fullPath: '/lead-tasks'
      preLoaderRoute: typeof LeadTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai-agents': {
      id: '/admin/ai-agents'
      path: '/ai-agents'
      fullPath: '/admin/ai-agents'
      preLoaderRoute: typeof AdminAiAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/amocrm-catalog': {
      id: '/admin/amocrm-catalog'
      path: '/amocrm-catalog'
      fullPath: '/admin/amocrm-catalog'
      preLoaderRoute: typeof AdminAmocrmCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/amocrm-disconnect': {
      id: '/admin/amocrm-disconnect'
      path: '/amocrm-disconnect'
      fullPath: '/admin/amocrm-disconnect'
      preLoaderRoute: typeof AdminAmocrmDisconnectRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/amocrm-import': {
      id: '/admin/amocrm-import'
      path: '/amocrm-import'
      fullPath: '/admin/amocrm-import'
      preLoaderRoute: typeof AdminAmocrmImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/amocrm-import-settings': {
      id: '/admin/amocrm-import-settings'
      path: '/amocrm-import-settings'
      fullPath: '/admin/amocrm-import-settings'
      preLoaderRoute: typeof AdminAmocrmImportSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auto-responders': {
      id: '/admin/auto-responders'
      path: '/auto-responders'
      fullPath: '/admin/auto-responders'
      preLoaderRoute: typeof AdminAutoRespondersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/create-employee': {
      id: '/admin/create-employee'
      path: '/create-employee'
      fullPath: '/admin/create-employee'
      preLoaderRoute: typeof AdminCreateEmployeeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delete-employee': {
      id: '/admin/delete-employee'
      path: '/delete-employee'
      fullPath: '/admin/delete-employee'
      preLoaderRoute: typeof AdminDeleteEmployeeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/org-structure': {
      id: '/admin/org-structure'
      path: '/org-structure'
      fullPath: '/admin/org-structure'
      preLoaderRoute: typeof AdminOrgStructureRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security-ban': {
      id: '/admin/security-ban'
      path: '/security-ban'
      fullPath: '/admin/security-ban'
      preLoaderRoute: typeof AdminSecurityBanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security-users': {
      id: '/admin/security-users'
      path: '/security-users'
      fullPath: '/admin/security-users'
      preLoaderRoute: typeof AdminSecurityUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/set-employee-password': {
      id: '/admin/set-employee-password'
      path: '/set-employee-password'
      fullPath: '/admin/set-employee-password'
      preLoaderRoute: typeof AdminSetEmployeePasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ai-assistant/chat': {
      id: '/ai-assistant/chat'
      path: '/chat'
      fullPath: '/ai-assistant/chat'
      preLoaderRoute: typeof AiAssistantChatRouteImport
      parentRoute: typeof AiAssistantRoute
    }
    '/audio-analytics/analyze': {
      id: '/audio-analytics/analyze'
      path: '/analyze'
      fullPath: '/audio-analytics/analyze'
      preLoaderRoute: typeof AudioAnalyticsAnalyzeRouteImport
      parentRoute: typeof AudioAnalyticsRoute
    }
    '/crm/companies': {
      id: '/crm/companies'
      path: '/crm/companies'
      fullPath: '/crm/companies'
      preLoaderRoute: typeof CrmCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/deals': {
      id: '/crm/deals'
      path: '/crm/deals'
      fullPath: '/crm/deals'
      preLoaderRoute: typeof CrmDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/pipeline': {
      id: '/crm/pipeline'
      path: '/crm/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof CrmPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/amocrm-tasks': {
      id: '/dashboard/amocrm-tasks'
      path: '/amocrm-tasks'
      fullPath: '/dashboard/amocrm-tasks'
      preLoaderRoute: typeof DashboardAmocrmTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/errors/log': {
      id: '/errors/log'
      path: '/errors/log'
      fullPath: '/errors/log'
      preLoaderRoute: typeof ErrorsLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/send-push': {
      id: '/notifications/send-push'
      path: '/notifications/send-push'
      fullPath: '/notifications/send-push'
      preLoaderRoute: typeof NotificationsSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/platform'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/activity': {
      id: '/platform/activity'
      path: '/platform/activity'
      fullPath: '/platform/activity'
      preLoaderRoute: typeof PlatformActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/add-employee': {
      id: '/platform/add-employee'
      path: '/platform/add-employee'
      fullPath: '/platform/add-employee'
      preLoaderRoute: typeof PlatformAddEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/ai': {
      id: '/platform/ai'
      path: '/platform/ai'
      fullPath: '/platform/ai'
      preLoaderRoute: typeof PlatformAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/create-organization': {
      id: '/platform/create-organization'
      path: '/platform/create-organization'
      fullPath: '/platform/create-organization'
      preLoaderRoute: typeof PlatformCreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/deactivate-expired-trials': {
      id: '/platform/deactivate-expired-trials'
      path: '/platform/deactivate-expired-trials'
      fullPath: '/platform/deactivate-expired-trials'
      preLoaderRoute: typeof PlatformDeactivateExpiredTrialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/delete-organization': {
      id: '/platform/delete-organization'
      path: '/platform/delete-organization'
      fullPath: '/platform/delete-organization'
      preLoaderRoute: typeof PlatformDeleteOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/delete-user': {
      id: '/platform/delete-user'
      path: '/platform/delete-user'
      fullPath: '/platform/delete-user'
      preLoaderRoute: typeof PlatformDeleteUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/errors': {
      id: '/platform/errors'
      path: '/platform/errors'
      fullPath: '/platform/errors'
      preLoaderRoute: typeof PlatformErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/integrations': {
      id: '/platform/integrations'
      path: '/platform/integrations'
      fullPath: '/platform/integrations'
      preLoaderRoute: typeof PlatformIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/notifications': {
      id: '/platform/notifications'
      path: '/platform/notifications'
      fullPath: '/platform/notifications'
      preLoaderRoute: typeof PlatformNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/update-user': {
      id: '/platform/update-user'
      path: '/platform/update-user'
      fullPath: '/platform/update-user'
      preLoaderRoute: typeof PlatformUpdateUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/users': {
      id: '/platform/users'
      path: '/platform/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof PlatformUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram/link': {
      id: '/telegram/link'
      path: '/telegram/link'
      fullPath: '/telegram/link'
      preLoaderRoute: typeof TelegramLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram/send-daily-report': {
      id: '/telegram/send-daily-report'
      path: '/telegram/send-daily-report'
      fullPath: '/telegram/send-daily-report'
      preLoaderRoute: typeof TelegramSendDailyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram/send-test': {
      id: '/telegram/send-test'
      path: '/telegram/send-test'
      fullPath: '/telegram/send-test'
      preLoaderRoute: typeof TelegramSendTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telegram/webhook': {
      id: '/telegram/webhook'
      path: '/telegram/webhook'
      fullPath: '/telegram/webhook'
      preLoaderRoute: typeof TelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/leads/': {
      id: '/crm/leads/'
      path: '/crm/leads'
      fullPath: '/crm/leads/'
      preLoaderRoute: typeof CrmLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/leads/$leadId': {
      id: '/crm/leads/$leadId'
      path: '/crm/leads/$leadId'
      fullPath: '/crm/leads/$leadId'
      preLoaderRoute: typeof CrmLeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/amocrm/callback': {
      id: '/integrations/amocrm/callback'
      path: '/amocrm/callback'
      fullPath: '/integrations/amocrm/callback'
      preLoaderRoute: typeof IntegrationsAmocrmCallbackRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/integrations/amocrm/connect': {
      id: '/integrations/amocrm/connect'
      path: '/amocrm/connect'
      fullPath: '/integrations/amocrm/connect'
      preLoaderRoute: typeof IntegrationsAmocrmConnectRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/integrations/amocrm/sync': {
      id: '/integrations/amocrm/sync'
      path: '/amocrm/sync'
      fullPath: '/integrations/amocrm/sync'
      preLoaderRoute: typeof IntegrationsAmocrmSyncRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/integrations/amocrm/sync-all': {
      id: '/integrations/amocrm/sync-all'
      path: '/amocrm/sync-all'
      fullPath: '/integrations/amocrm/sync-all'
      preLoaderRoute: typeof IntegrationsAmocrmSyncAllRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/integrations/amocrm/webhook': {
      id: '/integrations/amocrm/webhook'
      path: '/amocrm/webhook'
      fullPath: '/integrations/amocrm/webhook'
      preLoaderRoute: typeof IntegrationsAmocrmWebhookRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/platform/organizations/$orgId': {
      id: '/platform/organizations/$orgId'
      path: '/platform/organizations/$orgId'
      fullPath: '/platform/organizations/$orgId'
      preLoaderRoute: typeof PlatformOrganizationsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiAgentsRoute: typeof AdminAiAgentsRoute
  AdminAmocrmCatalogRoute: typeof AdminAmocrmCatalogRoute
  AdminAmocrmDisconnectRoute: typeof AdminAmocrmDisconnectRoute
  AdminAmocrmImportRoute: typeof AdminAmocrmImportRoute
  AdminAmocrmImportSettingsRoute: typeof AdminAmocrmImportSettingsRoute
  AdminAutoRespondersRoute: typeof AdminAutoRespondersRoute
  AdminCreateEmployeeRoute: typeof AdminCreateEmployeeRoute
  AdminDeleteEmployeeRoute: typeof AdminDeleteEmployeeRoute
  AdminOrgStructureRoute: typeof AdminOrgStructureRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSecurityBanRoute: typeof AdminSecurityBanRoute
  AdminSecurityUsersRoute: typeof AdminSecurityUsersRoute
  AdminSetEmployeePasswordRoute: typeof AdminSetEmployeePasswordRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiAgentsRoute: AdminAiAgentsRoute,
  AdminAmocrmCatalogRoute: AdminAmocrmCatalogRoute,
  AdminAmocrmDisconnectRoute: AdminAmocrmDisconnectRoute,
  AdminAmocrmImportRoute: AdminAmocrmImportRoute,
  AdminAmocrmImportSettingsRoute: AdminAmocrmImportSettingsRoute,
  AdminAutoRespondersRoute: AdminAutoRespondersRoute,
  AdminCreateEmployeeRoute: AdminCreateEmployeeRoute,
  AdminDeleteEmployeeRoute: AdminDeleteEmployeeRoute,
  AdminOrgStructureRoute: AdminOrgStructureRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSecurityBanRoute: AdminSecurityBanRoute,
  AdminSecurityUsersRoute: AdminSecurityUsersRoute,
  AdminSetEmployeePasswordRoute: AdminSetEmployeePasswordRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AiAssistantRouteChildren {
  AiAssistantChatRoute: typeof AiAssistantChatRoute
}

const AiAssistantRouteChildren: AiAssistantRouteChildren = {
  AiAssistantChatRoute: AiAssistantChatRoute,
}

const AiAssistantRouteWithChildren = AiAssistantRoute._addFileChildren(
  AiAssistantRouteChildren,
)

interface AudioAnalyticsRouteChildren {
  AudioAnalyticsAnalyzeRoute: typeof AudioAnalyticsAnalyzeRoute
}

const AudioAnalyticsRouteChildren: AudioAnalyticsRouteChildren = {
  AudioAnalyticsAnalyzeRoute: AudioAnalyticsAnalyzeRoute,
}

const AudioAnalyticsRouteWithChildren = AudioAnalyticsRoute._addFileChildren(
  AudioAnalyticsRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAmocrmTasksRoute: typeof DashboardAmocrmTasksRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAmocrmTasksRoute: DashboardAmocrmTasksRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface IntegrationsRouteChildren {
  IntegrationsAmocrmCallbackRoute: typeof IntegrationsAmocrmCallbackRoute
  IntegrationsAmocrmConnectRoute: typeof IntegrationsAmocrmConnectRoute
  IntegrationsAmocrmSyncRoute: typeof IntegrationsAmocrmSyncRoute
  IntegrationsAmocrmSyncAllRoute: typeof IntegrationsAmocrmSyncAllRoute
  IntegrationsAmocrmWebhookRoute: typeof IntegrationsAmocrmWebhookRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsAmocrmCallbackRoute: IntegrationsAmocrmCallbackRoute,
  IntegrationsAmocrmConnectRoute: IntegrationsAmocrmConnectRoute,
  IntegrationsAmocrmSyncRoute: IntegrationsAmocrmSyncRoute,
  IntegrationsAmocrmSyncAllRoute: IntegrationsAmocrmSyncAllRoute,
  IntegrationsAmocrmWebhookRoute: IntegrationsAmocrmWebhookRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AiAssistantRoute: AiAssistantRouteWithChildren,
  AttendanceRoute: AttendanceRoute,
  AudioAnalyticsRoute: AudioAnalyticsRouteWithChildren,
  CrmStagesRoute: CrmStagesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FunnelsRoute: FunnelsRoute,
  InboxRoute: InboxRoute,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  LeadAnalyticsRoute: LeadAnalyticsRoute,
  LeadTasksRoute: LeadTasksRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TasksRoute: TasksRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CrmCompaniesRoute: CrmCompaniesRoute,
  CrmContactsRoute: CrmContactsRoute,
  CrmDealsRoute: CrmDealsRoute,
  CrmPipelineRoute: CrmPipelineRoute,
  ErrorsLogRoute: ErrorsLogRoute,
  NotificationsSendPushRoute: NotificationsSendPushRoute,
  PlatformActivityRoute: PlatformActivityRoute,
  PlatformAddEmployeeRoute: PlatformAddEmployeeRoute,
  PlatformAiRoute: PlatformAiRoute,
  PlatformCreateOrganizationRoute: PlatformCreateOrganizationRoute,
  PlatformDeactivateExpiredTrialsRoute: PlatformDeactivateExpiredTrialsRoute,
  PlatformDeleteOrganizationRoute: PlatformDeleteOrganizationRoute,
  PlatformDeleteUserRoute: PlatformDeleteUserRoute,
  PlatformErrorsRoute: PlatformErrorsRoute,
  PlatformIntegrationsRoute: PlatformIntegrationsRoute,
  PlatformNotificationsRoute: PlatformNotificationsRoute,
  PlatformUpdateUserRoute: PlatformUpdateUserRoute,
  PlatformUsersRoute: PlatformUsersRoute,
  TelegramLinkRoute: TelegramLinkRoute,
  TelegramSendDailyReportRoute: TelegramSendDailyReportRoute,
  TelegramSendTestRoute: TelegramSendTestRoute,
  TelegramWebhookRoute: TelegramWebhookRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  CrmLeadsLeadIdRoute: CrmLeadsLeadIdRoute,
  PlatformOrganizationsOrgIdRoute: PlatformOrganizationsOrgIdRoute,
  CrmLeadsIndexRoute: CrmLeadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
