/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AudioAnalyticsRouteImport } from './routes/audio-analytics'
import { Route as CrmStagesRouteImport } from './routes/crm-stages'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FunnelsRouteImport } from './routes/funnels'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as LeadTasksRouteImport } from './routes/lead-tasks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as CrmCompaniesRouteImport } from './routes/crm.companies'
import { Route as CrmContactsRouteImport } from './routes/crm.contacts'
import { Route as CrmDealsRouteImport } from './routes/crm.deals'
import { Route as CrmPipelineRouteImport } from './routes/crm.pipeline'
import { Route as CrmLeadsIndexRouteImport } from './routes/crm.leads.index'
import { Route as CrmLeadsLeadIdRouteImport } from './routes/crm.leads.$leadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioAnalyticsRoute = AudioAnalyticsRouteImport.update({
  id: '/audio-analytics',
  path: '/audio-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmStagesRoute = CrmStagesRouteImport.update({
  id: '/crm-stages',
  path: '/crm-stages',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FunnelsRoute = FunnelsRouteImport.update({
  id: '/funnels',
  path: '/funnels',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadTasksRoute = LeadTasksRouteImport.update({
  id: '/lead-tasks',
  path: '/lead-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmCompaniesRoute = CrmCompaniesRouteImport.update({
  id: '/crm/companies',
  path: '/crm/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmContactsRoute = CrmContactsRouteImport.update({
  id: '/crm/contacts',
  path: '/crm/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmDealsRoute = CrmDealsRouteImport.update({
  id: '/crm/deals',
  path: '/crm/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmPipelineRoute = CrmPipelineRouteImport.update({
  id: '/crm/pipeline',
  path: '/crm/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsIndexRoute = CrmLeadsIndexRouteImport.update({
  id: '/crm/leads/',
  path: '/crm/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmLeadsLeadIdRoute = CrmLeadsLeadIdRouteImport.update({
  id: '/crm/leads/$leadId',
  path: '/crm/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/audio-analytics': typeof AudioAnalyticsRoute
  '/crm-stages': typeof CrmStagesRoute
  '/dashboard': typeof DashboardRoute
  '/funnels': typeof FunnelsRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/lead-tasks': typeof LeadTasksRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/leads/$leadId': typeof CrmLeadsLeadIdRoute
  '/crm/leads/': typeof CrmLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/audio-analytics': typeof AudioAnalyticsRoute
  '/crm-stages': typeof CrmStagesRoute
  '/dashboard': typeof DashboardRoute
  '/funnels': typeof FunnelsRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/lead-tasks': typeof LeadTasksRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/leads/$leadId': typeof CrmLeadsLeadIdRoute
  '/crm/leads': typeof CrmLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/audio-analytics': typeof AudioAnalyticsRoute
  '/crm-stages': typeof CrmStagesRoute
  '/dashboard': typeof DashboardRoute
  '/funnels': typeof FunnelsRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/lead-tasks': typeof LeadTasksRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/crm/companies': typeof CrmCompaniesRoute
  '/crm/contacts': typeof CrmContactsRoute
  '/crm/deals': typeof CrmDealsRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/leads/$leadId': typeof CrmLeadsLeadIdRoute
  '/crm/leads/': typeof CrmLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/audio-analytics'
    | '/crm-stages'
    | '/dashboard'
    | '/funnels'
    | '/inbox'
    | '/integrations'
    | '/lead-tasks'
    | '/login'
    | '/settings'
    | '/tasks'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/crm/pipeline'
    | '/crm/leads/$leadId'
    | '/crm/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/audio-analytics'
    | '/crm-stages'
    | '/dashboard'
    | '/funnels'
    | '/inbox'
    | '/integrations'
    | '/lead-tasks'
    | '/login'
    | '/settings'
    | '/tasks'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/crm/pipeline'
    | '/crm/leads/$leadId'
    | '/crm/leads'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/audio-analytics'
    | '/crm-stages'
    | '/dashboard'
    | '/funnels'
    | '/inbox'
    | '/integrations'
    | '/lead-tasks'
    | '/login'
    | '/settings'
    | '/tasks'
    | '/crm/companies'
    | '/crm/contacts'
    | '/crm/deals'
    | '/crm/pipeline'
    | '/crm/leads/$leadId'
    | '/crm/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AudioAnalyticsRoute: typeof AudioAnalyticsRoute
  CrmStagesRoute: typeof CrmStagesRoute
  DashboardRoute: typeof DashboardRoute
  FunnelsRoute: typeof FunnelsRoute
  InboxRoute: typeof InboxRoute
  IntegrationsRoute: typeof IntegrationsRoute
  LeadTasksRoute: typeof LeadTasksRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  CrmCompaniesRoute: typeof CrmCompaniesRoute
  CrmContactsRoute: typeof CrmContactsRoute
  CrmDealsRoute: typeof CrmDealsRoute
  CrmPipelineRoute: typeof CrmPipelineRoute
  CrmLeadsLeadIdRoute: typeof CrmLeadsLeadIdRoute
  CrmLeadsIndexRoute: typeof CrmLeadsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-analytics': {
      id: '/audio-analytics'
      path: '/audio-analytics'
      fullPath: '/audio-analytics'
      preLoaderRoute: typeof AudioAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm-stages': {
      id: '/crm-stages'
      path: '/crm-stages'
      fullPath: '/crm-stages'
      preLoaderRoute: typeof CrmStagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funnels': {
      id: '/funnels'
      path: '/funnels'
      fullPath: '/funnels'
      preLoaderRoute: typeof FunnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lead-tasks': {
      id: '/lead-tasks'
      path: '/lead-tasks'
      fullPath: '/lead-tasks'
      preLoaderRoute: typeof LeadTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/companies': {
      id: '/crm/companies'
      path: '/crm/companies'
      fullPath: '/crm/companies'
      preLoaderRoute: typeof CrmCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/contacts': {
      id: '/crm/contacts'
      path: '/crm/contacts'
      fullPath: '/crm/contacts'
      preLoaderRoute: typeof CrmContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/deals': {
      id: '/crm/deals'
      path: '/crm/deals'
      fullPath: '/crm/deals'
      preLoaderRoute: typeof CrmDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/pipeline': {
      id: '/crm/pipeline'
      path: '/crm/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof CrmPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/leads/': {
      id: '/crm/leads/'
      path: '/crm/leads'
      fullPath: '/crm/leads/'
      preLoaderRoute: typeof CrmLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/leads/$leadId': {
      id: '/crm/leads/$leadId'
      path: '/crm/leads/$leadId'
      fullPath: '/crm/leads/$leadId'
      preLoaderRoute: typeof CrmLeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  AudioAnalyticsRoute: AudioAnalyticsRoute,
  CrmStagesRoute: CrmStagesRoute,
  DashboardRoute: DashboardRoute,
  FunnelsRoute: FunnelsRoute,
  InboxRoute: InboxRoute,
  IntegrationsRoute: IntegrationsRoute,
  LeadTasksRoute: LeadTasksRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  CrmCompaniesRoute: CrmCompaniesRoute,
  CrmContactsRoute: CrmContactsRoute,
  CrmDealsRoute: CrmDealsRoute,
  CrmPipelineRoute: CrmPipelineRoute,
  CrmLeadsLeadIdRoute: CrmLeadsLeadIdRoute,
  CrmLeadsIndexRoute: CrmLeadsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
